name: Bradley Campbell, Web Developer
markdown: kramdown
url: http://www.redknightnz81.com
baseurl: /
permalink: /blog/:year/:month/:day/:title
collections:
  designmockups:
    output: true
    permalink: /designs/:title