name: Bradley Campbell, Web Developer
description: Website of Bradley Campbell.  Front end developer based in Wellington, New Zealand.
title: Portfolio website of Bradley Campbell, front end web developer based in Wellington, New Zealand.
markdown: kramdown
url: http://www.redknightnz81.com
baseurl: /
permalink: /blog/:year/:month/:day/:title
collections:
  designmockups:
    output: true
    permalink: /designs/:title
navigation:
  - title: HOME
    url: http://www.redknightnz81.com/
    new_window: false
  - title: BLOG
    url: /blog/
    new_window: false
  - title: DESIGNS
    url: /designs/
    new_window: false
  - title: TWITTER
    url: http://www.twitter.com/redknightnz81
    new_window: true